# Generated by Django 4.2.7 on 2023-11-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='added_to_favorite',
            field=models.IntegerField(default=0, verbose_name='Добавлено в избранное'),
        ),
    ]
