# Generated by Django 4.2.7 on 2023-11-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_added_to_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='added_to_favorite',
        ),
    ]
